version: '2'

services:

  bro:
    image: blacktop/bro:latest
    command: -i wlp2s0
    volumes:
      - ./bro/data:/pcap:rw
    environment:
      - 'TZ=Europe/Brussels'
    cap_add:
      - NET_RAW
    network_mode: host

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - 'ES_JAVA_OPTS=-Xmx256m -Xms256m'
      - 'TZ=Europe/Brussels'
    networks:
      - elk
    depends_on:
      - bro

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./bro/data:/usr/share/logstash/bro:ro
    ports:
      - "5000:5000"
    environment:
      - 'LS_JAVA_OPTS=-Xmx256m -Xms256m'
      - 'TZ=Europe/Brussels'
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    environment:
      - 'TZ=Europe/Brussels'
    networks:
      - elk
    depends_on:
      - elasticsearch

  # metricbeat:
  #   image: docker.elastic.co/beats/metricbeat:6.4.3
  #   volumes:
  #     - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/config/metricbeat.yml:ro
  #   environment:
  #     - 'TZ=Europe/Brussels'
  #   depends_on:
  #     - elasticsearch

  # heartbeat:
  #   image: docker.elastic.co/beats/heartbeat:6.4.3
  #   volumes:
  #     - ./heartbeat/heartbeat.yml:/usr/share/heartbeat/config/heartbeat.yml:ro
  #   environment:
  #     - 'TZ=Europe/Brussels'
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  # packetbeat:
  #   image: docker.elastic.co/beats/packetbeat:6.4.3
  #   volumes:
  #     - ./packetbeat/packetbeat.yml:/usr/share/packetbeat/config/packetbeat.yml:ro
  #   environment:
  #     - 'TZ=Europe/Brussels'
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  # ergo-witness:
  #   build:
  #     context: ergo-witness/
  #   volumes:
  #     - ./ergo-witness:/usr/share/ergo-witness/:ro
  #   environment:
  #     - 'TZ=Europe/Brussels'
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  mariadb:
    image: mariadb:10.4.0-bionic
    volumes:
      - ./dofler/db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=dofler'
      - 'MYSQL_DATABASE=dofler'
      - 'MYSQL_USER=dofler'
      - 'MYSQL_PASSWORD=dofler'
      - 'TZ=Europe/Brussels'
    networks:
      - elk

  dofler:
    build:
      context: dofler/
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - 'TZ=Europe/Brussels'
    network_mode: host
    privileged: true
    depends_on:
      - mariadb

  ctfd:
    image: ctfd/ctfd
    ports:
      - "8000:8000"
    environment:
      - 'TZ=Europe/Brussels'

networks:

  elk:
    driver: bridge
